name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-action:
    name: Validate GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Action
        uses: mpalmer/action-validator@v1.5.0
        with:
          path: action.yml

  format-check:
    name: Format Check (dprint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dprint
        uses: dprint/check@v2.2

  validate-shell:
    name: Validate Shell Scripts
    runs-on: ubuntu-latest
    if: ${{ hashFiles('**/*.sh') != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "."
